Repository woowa-techcamp-2021/cashbook-5, pull requests merged in 2021-07, with the labels that each got.

#2 chore: Base Code for Observer Pattern
  client/src/components/header/header.ts
  client/src/interfaces/Component.ts
  client/src/models/Canlendar.ts
  client/src/models/Observer.ts
Labels: good first issue

#3 Base 코드 Main Branch로 머지
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  client/babel.config.json
  client/package-lock.json
  client/package.json
  client/src/components/header/header.scss
  client/src/components/header/header.ts
  client/src/core/router.ts
  client/src/core/routerHelper.ts
  client/src/index.html
  client/src/index.ts
  client/src/interfaces/Component.ts
  client/src/models/Canlendar.ts
  client/src/models/Observer.ts
  client/src/normalize.css
  client/src/pages/index.ts
  client/src/pages/main/index.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: good first issue

#18 [BE] Express 서버 세팅 작업
  server/package-lock.json
  server/package.json
  server/src/api/index.ts
  server/src/app.ts
  server/src/config/webpack.config.js
  server/tsconfig.json
Labels: BE

#21 [#4] fix : Header Import 수정
  client/src/index.ts
Labels: bug

#27 chore: Pie Chart 나타날때 애니메이션 효과 추가
  client/src/pages/StatisticPage/index.ts
  client/src/utils/PieChart.ts
Labels: FE

#31 [#22]feat: ledger 입력 모달 개발 + TypeSafety한 Component 적용(Generic으로 State, Prop Interface 받도록 수정)
  client/src/components/Header/index.scss
  client/src/components/Header/index.ts
  client/src/components/LedgerAddButton/index.scss
  client/src/components/LedgerAddButton/index.ts
  client/src/components/LedgerAddModal/CategorySelector/index.scss
  client/src/components/LedgerAddModal/CategorySelector/index.ts
  client/src/components/LedgerAddModal/index.scss
  client/src/components/LedgerAddModal/index.ts
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.ts
  client/src/components/LedgerList/index.ts
  client/src/core/Component.ts
  client/src/interfaces/Category.ts
  client/src/interfaces/Ledger.ts
  client/src/pages/MainPage/index.scss
  client/src/pages/MainPage/index.ts
  client/src/pages/StatisticPage/index.ts
Labels: FE

#32 [#29] feat : LedgerBody 구현
  client/src/components/Header/index.ts
  client/src/components/LedgerContainer/index.scss
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.ts
  client/src/components/LedgerList/index.scss
  client/src/components/LedgerList/index.ts
  client/src/components/MonthPicker.ts
  client/src/components/SnackBar/index.scss
  client/src/components/SnackBar/index.ts
  client/src/global.scss
  client/src/index.ts
  client/src/interfaces/Ledger.ts
  client/src/models/Ledgers.ts
  client/src/utils/codeHelper.ts
Labels: FE

#33 [#22] feat: Ledger 입력 화면 개발(카드 선택 기능)
  client/src/components/LedgerAddModal/CardTypeSelector/index.scss
  client/src/components/LedgerAddModal/CardTypeSelector/index.ts
  client/src/components/LedgerAddModal/CategorySelector/index.scss
  client/src/components/LedgerAddModal/CategorySelector/index.ts
  client/src/components/LedgerAddModal/index.scss
  client/src/components/LedgerAddModal/index.ts
  client/src/global.scss
  client/src/interfaces/CardType.ts
  client/src/pages/MainPage/index.ts
  client/src/utils/selecthelper.ts
Labels: FE

#37 add: wallat page and navigation button( + icon)
  client/src/assets/svg.ts
  client/src/components/Header/index.ts
  client/src/index.ts
  client/src/pages/MainPage/index.ts
  client/src/pages/WalletPage/index.scss
  client/src/pages/WalletPage/index.ts
  client/src/pages/index.ts
Labels: FE

#38 [#7] feat : 캘린더 Ledger Data 접근 및 UI 개선
  client/src/components/Calendar/index.scss
  client/src/components/Calendar/index.ts
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.ts
  client/src/components/LedgerList/index.ts
  client/src/pages/CalendarPage/index.scss
  client/src/utils/codeHelper.ts
Labels: FE

#39 style : max-width 수정
  client/src/components/Header/index.scss
  client/src/components/LedgerAddModal/CardTypeSelector/index.scss
  client/src/components/LedgerAddModal/index.scss
  client/src/global.scss
  client/src/pages/StatisticPage/index.scss
Labels: FE

#40 style : 다크모드 색상변경
  client/src/components/Calendar/index.scss
  client/src/components/Header/index.scss
  client/src/global.scss
Labels: FE

#41 [#35] feat: 결제 수단 추가를 위한 Wallet Page 완성
  client/src/api/paymentTypeAPI.ts
  client/src/components/LedgerAddModal/CategorySelector/index.scss
  client/src/components/LedgerAddModal/index.scss
  client/src/components/PaymentTypeAddModal/index.scss
  client/src/components/PaymentTypeAddModal/index.ts
  client/src/pages/StatisticPage/index.scss
  client/src/pages/WalletPage/index.scss
  client/src/pages/WalletPage/index.ts
Labels: FE

#43 fix: color picker overflow 수정(flex-wrap)
  client/src/components/PaymentTypeAddModal/index.scss
  client/src/components/PaymentTypeAddModal/index.ts
Labels: FE

#45 [#44] feat : 날짜 관련 컴포넌트 옵저버 Subscription 기능 추가
  client/src/components/Calendar/index.scss
  client/src/components/Header/index.scss
  client/src/components/Header/index.ts
  client/src/components/LedgerContainer/index.scss
  client/src/components/MonthPicker.ts
  client/src/global.scss
  client/src/models/Calendar.ts
Labels: FE

#46 chore: Modal 관련 Style 수정
  client/src/components/LedgerAddButton/index.scss
  client/src/components/LedgerAddModal/CardTypeSelector/index.scss
  client/src/components/LedgerAddModal/CardTypeSelector/index.ts
  client/src/components/LedgerAddModal/CategorySelector/index.scss
  client/src/components/LedgerAddModal/CategorySelector/index.ts
  client/src/components/LedgerAddModal/index.scss
  client/src/components/LedgerAddModal/index.ts
  client/src/pages/WalletPage/index.scss
  client/src/pages/WalletPage/index.ts
Labels: bug
