Repository woowa-techcamp-2021/cashbook-5, pull requests merged in 2021-08, with the labels that each got.

#47 LineChart 구현
  client/package-lock.json
  client/package.json
  client/src/interfaces/Ledger.ts
  client/src/pages/StatisticPage/index.scss
  client/src/pages/StatisticPage/index.ts
  client/src/utils/charts/LineChart.ts
  client/src/utils/charts/PieChart.ts
  client/src/utils/charts/duration.ts
  client/src/utils/charts/scale.ts
  client/src/utils/charts/svgElement.ts
Labels: FE

#51 [#50] 캘린더 페이지 리팩토링
  client/src/api/ledgerAPI.ts
  client/src/components/Calendar/index.scss
  client/src/components/Calendar/index.ts
  client/src/components/LedgerContainer/index.ts
  client/src/components/MonthPicker.ts
  client/src/components/SnackBar/index.scss
  client/src/models/Ledgers.ts
  client/src/pages/CalendarPage/index.ts
  client/src/pages/MainPage/index.ts
Labels: FE, bug

#56 [#9] 라인차트 여러 카테고리를 동시에 보여주는 기능 추가 구현
  client/src/pages/StatisticPage/index.ts
  client/src/utils/charts/LineChart.ts
  client/src/utils/charts/PieChart.ts
Labels: FE

#62 [#61] feat: userLedgersByMonth api추가
  client/src/index.html
  server/src/controllers/ledger.controller.ts
  server/src/models/ledger.model.ts
  server/src/repositories/ledger.repository.ts
  server/src/router/index.ts
  server/src/router/ledger.router.ts
  server/src/services/ledger.service.ts
Labels: BE

#64 [#63] feat: 리프레시 토큰 추가
  server/src/controllers/auth.controller.ts
  server/src/middleware/auth.middleware.ts
  server/src/models/user.model.ts
  server/src/repositories/user.repository.ts
  server/src/services/jwt.service.ts
  server/src/services/user.service.ts
Labels: BE

#69 [#68] Category 관련 Controller, Service, Repository 구현
  server/src/controllers/auth.controller.ts
  server/src/controllers/category.controller.ts
  server/src/controllers/ledger.controller.ts
  server/src/controllers/user.controller.ts
  server/src/repositories/category.repository.ts
  server/src/router/category.router.ts
  server/src/router/index.ts
  server/src/services/category.service.ts
  server/src/utils/HttpStatus.ts
Labels: BE

#70 [#67] PaymentType 관련 Controller, Service, Repository 생성
  server/src/controllers/category.controller.ts
  server/src/controllers/ledger.controller.ts
  server/src/controllers/paymentType.controller.ts
  server/src/dto/CategoryDTO.ts
  server/src/dto/LedgerDTO.ts
  server/src/dto/PaymentTypeDTO.ts
  server/src/loaders/sequelize.loaders.ts
  server/src/middleware/auth.middleware.ts
  server/src/models/index.ts
  server/src/models/init_data.ts
  server/src/models/ledger.model.ts
  server/src/models/paymenttype.model.ts
  server/src/models/user.model.ts
  server/src/repositories/category.repository.ts
  server/src/repositories/ledger.repository.ts
  server/src/repositories/paymentType.repository.ts
  server/src/repositories/user.repository.ts
  server/src/router/category.router.ts
  server/src/router/index.ts
  server/src/router/ledger.router.ts
  server/src/router/paymentType.router.ts
  server/src/services/category.service.ts
  server/src/services/ledger.service.ts
  server/src/services/paymentType.service.ts
Labels: BE

#84 [#71] Ledgers data Type 변경
  server/src/controllers/ledger.controller.ts
  server/src/dto/LedgerDTO.ts
  server/src/models/category.model.ts
  server/src/models/ledger.model.ts
  server/src/repositories/ledger.repository.ts
  server/src/router/ledger.router.ts
  server/src/services/ledger.service.ts
Labels: BE

#85 [#83] feat : ledger API에 따른 프론트 코드 refactor
  client/src/api/ledgerAPI.ts
  client/src/components/Calendar/index.ts
  client/src/components/Header/index.ts
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.ts
  client/src/components/LedgerList/index.ts
  client/src/core/Component.ts
  client/src/interfaces/Ledger.ts
  client/src/models/Ledgers.ts
  client/src/models/Observer.ts
  client/src/pages/CalendarPage/index.ts
  client/src/pages/MainPage/index.ts
  client/src/utils/calendar.ts
Labels: FE

#89 [#76] 통계 그래프를 그리기위한 데이터 조회 API 구현과 FE 연결작업
  client/src/api/fetch.ts
  client/src/api/statisticAPI.ts
  client/src/pages/StatisticPage/index.ts
  server/src/controllers/ledger.controller.ts
  server/src/db/sequlze.ts
  server/src/dto/LedgerDTO.ts
  server/src/repositories/ledger.repository.ts
  server/src/router/ledger.router.ts
  server/src/services/ledger.service.ts
Labels: BE

#92 [#91] fix : 로그인 버튼 클릭시 href url 서버에서 가져오는 형태로 변경
  client/src/api/loginAPI.ts
  client/src/components/LoginModal/index.ts
  server/src/controllers/auth.controller.ts
  server/src/router/auth.router.ts
Labels: BE, FE

#96 feat: 배포용 백엔드 수정
  server/src/controllers/user.controller.ts
  server/src/db/sequlze.ts
  server/src/repositories/user.repository.ts
Labels: BE

#98 Webpack File 개발/배포용 나누기
  client/package-lock.json
  client/package.json
  client/src/components/Calendar/index.ts
  client/src/components/LedgerAddModal/CardTypeSelector/index.ts
  client/src/core/router.ts
  client/src/utils/selectHelper.ts
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/src/config/sequelize-mysql.yaml
  server/src/config/sequelize-sqlite.yaml
Labels: FE

#102 [#101] Amount 입력 Input 범위 제한시키기 (스낵바를 이용해서 사용자에게 전달)
  client/src/components/LedgerAddModal/index.ts
Labels: FE

#107 [#75] feat : 메인화면 가계부 수정삭제 버튼 추가 및 fe 디자인수정
  client/src/components/Calendar/index.scss
  client/src/components/Calendar/index.ts
  client/src/components/Header/index.scss
  client/src/components/Header/index.ts
  client/src/components/LedgerContainer/index.scss
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.scss
  client/src/components/LedgerItem/index.ts
  client/src/components/LedgerList/index.scss
  client/src/components/LedgerList/index.ts
  client/src/components/MonthPicker.ts
  client/src/global.scss
  client/src/index.html
  client/src/pages/StatisticPage/index.scss
  client/src/pages/WalletPage/index.scss
Labels: FE

#110 [#75] feat : 가계부 수정기능추가
  client/src/api/fetch.ts
  client/src/api/ledgerAPI.ts
  client/src/components/LedgerAddModal/index.ts
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.ts
  client/src/interfaces/Ledger.ts
  client/src/pages/MainPage/index.ts
Labels: FE

#112 [#113] style : 헤더, 메인, addModal ui 수정
  client/src/components/Header/index.scss
  client/src/components/Header/index.ts
  client/src/components/LedgerAddModal/CategorySelector/index.scss
  client/src/components/LedgerAddModal/index.scss
  client/src/components/LedgerAddModal/index.ts
  client/src/components/LedgerContainer/index.scss
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.ts
  client/src/components/LedgerList/index.ts
Labels: FE

#116 [#113] feat : 프론트 ui 변경작업
  client/package.json
  client/src/api/ledgerAPI.ts
  client/src/api/loginAPI.ts
  client/src/components/ConfirmDialog/index.scss
  client/src/components/ConfirmDialog/index.ts
  client/src/components/Header/index.scss
  client/src/components/Header/index.ts
  client/src/components/LedgerContainer/index.scss
  client/src/components/LedgerContainer/index.ts
  client/src/components/LedgerItem/index.scss
  client/src/components/LoginModal/index.scss
  client/src/global.scss
  client/src/pages/MainPage/index.ts
  client/src/pages/StatisticPage/CategoryList/index.scss
  client/src/pages/StatisticPage/CategoryList/index.ts
  client/src/pages/StatisticPage/index.scss
  client/src/pages/StatisticPage/index.ts
  client/src/pages/WalletPage/index.scss
  client/webpack.common.js
Labels: BE

#120 feat : UI 수정
  client/src/components/Header/index.scss
  client/src/components/Header/index.ts
  client/src/components/LedgerContainer/index.ts
  client/src/components/SnackBar/index.scss
  client/src/global.scss
  client/src/index.html
  client/src/pages/StatisticPage/CategoryList/index.scss
  client/src/pages/StatisticPage/CategoryList/index.ts
  client/src/pages/StatisticPage/index.ts
Labels: FE

#122 fix : git 아바타 클릭시 라우팅 안되는 오류 수정
  client/src/components/Header/index.ts
Labels: bug

#121 배포 스크립트 수정
  deploy.sh
Labels: BE

#127 [#126] feat : 최초 회원가입시 기본데이터 추가
  server/src/repositories/ledger.repository.ts
  server/src/repositories/paymentType.repository.ts
  server/src/repositories/user.repository.ts
Labels: BE
